sudo: required
dist: trusty
before_install:
  - curl https://raw.githubusercontent.com/scala-native/scala-native/v0.3.6/bin/travis_setup.sh | bash -x
addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache

language: scala

scala:
  - "2.10.7"
  - "2.11.12"
  - "2.12.6"
  - "2.13.0-M4"

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test mimaReportBinaryIssues

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -exec rm {} +
  - find $HOME/.ivy2 -name "ivydata-*.properties" -exec rm {} +
